# schema version
version = 3
# settings common for all profiles
backup_base_dir = 'C:\Users\Mac\Backup'

# setting for individual profiles - override any common ones

["My Documents"]
source_dir = 'C:\Users\Mac\Documents'
excluded_files = ['My Music\**', 'My Pictures\**', 'My Videos\**', '**\desktop.ini', '**\Thumbs.db']

[Desktop]
source_dir = 'C:\Users\Mac\Desktop'
excluded_files = ['**\desktop.ini', '**\*.exe', '**\*.msi']

["# this profile's name starts with a hash, therefore it will be ignored"]
source_dir = "this setting won't be loaded"

[rumardb]
# profile to back up 'rumar.sqlite' itself, e.g., with each `rumar.py c -a`
source_dir = '{backup_base_dir}'
included_files = ['rumar.sqlite']
checksum_comparison_if_same_size = true
archive_format = 'tar.xz'
compression_level = 4
db_path = ''
